#!/bin/bash
set -eux
set -o pipefail

# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Release a Debusine build from a ci child workspace into the Debusine prod
# workspace

# Run inside the container created with `lib/prepare-debusine`

# Dependencies:
#   `debusine` incus container (Debusine will be configured)

# Inputs:
#   DEBUSINE_HOST
#   DEBUSINE_SCOPE
#   DEBUSINE_TOKEN
#   DEBUSINE_CI_WORKSPACE
#   SRCPKG_NAME
#   SRCPKG_VERSION
#   SUITE

# Outputs:
#   None

echo "::group::Release to Debusine prod"

mkdir -p ~/.config/debusine/client
( umask 077; cat > ~/.config/debusine/client/config.ini <<EOF
[General]
default-server = default

[server:default]
api-url = https://${DEBUSINE_HOST}/api
scope = ${DEBUSINE_SCOPE}
token = ${DEBUSINE_TOKEN}
default-workspace = prod
EOF
)

suite_id=$(
  debusine collection list -w "$DEBUSINE_CI_WORKSPACE" --yaml |
  yq -r --arg suite "$SUITE" '
    map(select(.category == "debian:suite" and .name == $suite)) as $m
    | if ($m | length) == 1
      then $m[0].id
      else error("expected exactly one match")
      end
  '
)
workflow_id=$(debusine workflow start -w prod --yaml package-publish <<END|yq -r .id
source_artifact: ${suite_id}@collections/${SRCPKG_NAME}_${SRCPKG_VERSION}
binary_artifacts:
  category: debian:binary-package
  collection: ${suite_id}@collections
target_suite: ${SUITE}@debian:suite
END
)
debusine-action/lib/poll_workflow.py "$workflow_id"

echo "::endgroup::"
